os: linux
language: go
go:
    - 1.14.x
    
services:
    - postgres
before_script:
  - psql -c "create database test;create USER test WITH PASSWORD 'test';" -U postgres
script:
    - go test -v
    