os: linux
language: go
go:
    - 1.14.x
    
services:
    - postgres
before_script:
  - PSQL -c 'create user test WITH PASSWORD "test"' -U postgres
  - psql -c 'create database test;' -U postgres
script:
    - go test -v
    